databases:
  - name: smart-attendance-db
    plan: free
    databaseName: smart_attendance
    user: smart_attendance_user

services:
  - type: web
    name: smatten
    runtime: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: smart-attendance-db
          property: connectionString
